version: 2.1
jobs:
  build-and-push-dockerhub:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build and tag image
          command: |
            docker build -t $DOCKER_REPO:${CIRCLE_SHA1} .
      - run:
          name: Push images
          command: |
            docker push $DOCKER_REPO -a
  ruff-check:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Ruff
          command: pip install ruff
      - run:
          name: Run Ruff
          command: ruff check .
workflows:
  ci:
    when: pipeline.event.name == "pull_request" and pipeline.event.action == "opened"
    jobs:
      - ruff-check
  cd:
    jobs:
      - build-and-push-dockerhub:
          filters:
            branches:
              only: main
